#!/bin/bash

#https://github.com/kai3341/mkvksnd

function depcheck {
	for DEP in ffmpeg base64
	do
		[ -z "$(which "$DEP")" ] && (echo "Error: $DEP not found. Please install $DEP and try again." && FAIL="1")
	done
	[ -n "$FAIL" ] && exit 1
}

function printhelp {
	echo "USAGE: $(basename $0) -d /path/to/directory -o /out/file/name.vksnd"
	echo "Default directory './'; default outputfile 'out.vksnd'"
	echo "In the directory should contain files \"msg\" \"new\" \"on\" in any format supported by ffmpeg"
	exit 1
}

function argcheck {
	[ -z "$DIRPATH" ] && DIRPATH="./"
	[ -z "$OUTPUTFILE" ] && OUTPUTFILE="out.vksnd"
	[ -d "$DIRPATH" ] || (echo "Error: directory $DIRPATH not exist." && printhelp)
}

function argparse {
	while [[ $# > 1 ]]
	do
		key="$1"
		shift

		case $key in
			-d|--dir)
				DIRPATH="$1"
				shift
			;;
			-o|--out)
				OUTPUTFILE="$(echo $1|sed 's/\.vksnd$//g;s/$/.vksnd/g')"
				shift
			;;
			*)
				printhelp
			;;
		esac
	done
}

function CalcBASE64 {
	i=1
	for FORMAT in wav mp3
	do
		for FILE in msg new on
		do
			FILECURRENTFORMAT="$(ls -1|grep -i ^"$FILE"|grep -i "$FORMAT"|head -n1)"
			if [ -n "$FILECURRENTFORMAT" ]
			then
				BASE64["$i"]="$(base64 "$FILECURRENTFORMAT"|tr -d '\n')"
			else
				CURRENTFILE="$(ls -1|grep -i ^"$FILE"|head -n1)"
				CURRENTFILENAME="$(echo $CURRENTFILE|sed 's/\..*$//g')"
				ffmpeg -i "$CURRENTFILE" "$CURRENTFILENAME"".""$FORMAT"
				BASE64["$i"]="$(base64 "$CURRENTFILENAME"."$FORMAT"|tr -d '\n')"
			fi
			((i++))
		done
	done
}

function CreateVKSND {
	i=1
	j=1
	FORMAT=([1]="wav" [2]="mp3")
	SECTION=([1]="" [2]="_mp3")
	printf "{\nName:'noname'" > "$OUTPUTFILE"
	while ((j<=2))
	do
		for SUBSECTION in On New Msg
		do
			printf ",\n  ""$SUBSECTION""${SECTION["$j"]}"":'data:audio/""${FORMAT["$j"]}"";base64,""${BASE64["$i"]}""'" >> "$OUTPUTFILE"
			((i++))
		done
		((j++))
	done
	printf '\n}' >> "$OUTPUTFILE"
}

depcheck
argparse
argcheck
cd "$DIRPATH"
CalcBASE64
CreateVKSND
